services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./start-ollama.sh:/start-ollama.sh
    entrypoint: ["/bin/sh", "/start-ollama.sh"]

  app:
    build: .
    depends_on:
      - ollama
    volumes:
      - /root/ps-team-stealer/app:/app
    environment:
      - OLLAMA_URL=http://ollama:11434

volumes:
  ollama_data: 